### ISSUE TITLE
pro sections don't show

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/Zerius#22]
These include portfolio, packages, subscribe and ribbons
http://themeisle.com/forums/topic/how-to-migrate-zerif-lite-site-to-zerif-pro/

**Comment by rodica-andronache** [comment]
@ineagu we should fix this, right?

**Comment by ineagu** [comment]
yep

On Thu, Apr 7, 2016 at 4:22 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> we should fix this, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Zerius/issues/22#issuecomment-206898333>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
